import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <h1>Next.js Template</h1>
        <p>tailwind</p>
        <p>typescript</p>
      </div>
    </div>
  );
};

export default Home;
